linters:
  LineLength:
    max: 180
  ConsecutiveComments: # I disagree
    enabled: false
  SpaceInsideHashAttributes:
    style: no_space
  FinalNewline:
    enabled: false
  IdNames:
    style: snake_case

  RuboCop:
    ignored_cops:
      - Style/NestedParenthesizedCalls
      - Style/UnneededInterpolation
      - Lint/BlockAlignment
      - Lint/EndAlignment
      - Lint/Void
      - Metrics/LineLength
      - Metrics/BlockLength
      - Style/AlignParameters
      - Style/BlockNesting
      - Style/ElseAlignment
      - Style/FileName
      - Style/FinalNewline
      - Style/FrozenStringLiteralComment
      - Style/IfUnlessModifier
      - Style/IndentationWidth
      - Style/Next
      - Layout/TrailingBlankLines
      - Style/TrailingWhitespace
      - Style/WhileUntilModifier
      - Rails/OutputSafety # don't disagree, just need to investigate alternatives
