require: rubocop-rspec

AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*.rb
    - config/deploy/*
    - coverage
    - vendor/**/*

Rails:
  Enabled: true

LineLength:
  Max: 120

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

MethodLength:
  Max: 18

AbcSize:
  Max: 30

BlockLength:
  Max: 30
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'
    - 'lib/tasks/testcode.rake'

PerceivedComplexity:
  Max: 10

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Documentation: # format too restricted
  Enabled: false

Layout/EndOfLine:
  Enabled: false # restore when editor sorted out

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/DescribedClass:
  Enabled: false # prefer class name for readability

RSpec/MultipleDescribes:
  Enabled: false # conflicts with legit class names

RSpec/MultipleExpectations:
  Max: 3 # todo: this should be 2

RSpec/NestedGroups:
  Max: 4

RSpec/PredicateMatcher:
  Enabled: false # picks up legit method names

Style/EmptyMethod:
  EnforcedStyle: expanded

Bundler/OrderedGems:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false # too many legit exceptions

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Capfile'

AccessorMethodName:
  Exclude:
    - 'app/controllers/local_devise/*.rb'

Style/ColonMethodCall:
  Exclude:
    - 'app/models/user.rb'
