require: rubocop-rspec

AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*.rb

Rails:
  Enabled: true

LineLength:
  Max: 120

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

MethodLength:
  Max: 18

AbcSize:
  Max: 30

BlockLength:
  Max: 30
  Exclude:
    - 'Gemfile'

PerceivedComplexity:
  Max: 10

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Documentation: # format too restricted
  Enabled: false

Layout/EndOfLine:
  Enabled: false # restore when editor sorted out

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/DescribedClass:
  Enabled: false # prefer class name for readability

RSpec/MultipleDescribes:
  Enabled: false # conflicts with legit class names

RSpec/MultipleExpectations:
  Max: 3 # todo: this should be 2

RSpec/NestedGroups:
  Max: 4

Style/FileName:
  Exclude:
    - 'Gemfile'
    - 'Capfile'

Bundler/OrderedGems:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false
