AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb

LineLength:
  Max: 120

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

MethodLength:
  Max: 18

AbcSize:
  Max: 30

PerceivedComplexity:
  Max: 10

EmptyLinesAroundModuleBody: # prefer empty line for legibility
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

EmptyLinesAroundMethodBody:
  Enabled: false

Documentation: # format too restricted
  Enabled: false

# bug in current rubocop release 0.21.0
Delegate:
  Enabled: false

