require: rubocop-rspec

AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*.rb

Rails:
  Enabled: true

LineLength:
  Max: 120

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

MethodLength:
  Max: 18

AbcSize:
  Max: 30

PerceivedComplexity:
  Max: 10

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Documentation: # format too restricted
  Enabled: false

Style/EndOfLine:
  Enabled: false # restore when editor sorted out

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/DescribedClass:
  Enabled: false # prefer class name for readability

RSpec/MultipleDescribes:
  Enabled: false # conflicts with legit class names

Delegate:
  Enabled: false
