language: ruby

rvm:
- 2.2.5

services:
  - mysql

script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/application.travis.yml config/application.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - mysql -e 'CREATE DATABASE IF NOT EXISTS rails4eg_test;'
