branch-defaults:
  eb-test:
    environment: r4eg-dev
global:
  application_name: r4eg
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.1 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
